/* Generated By:JavaCC: Do not edit this line. DefaultParserConstants.java */
package org.smartfrog.sfcore.languages.sf;

public interface DefaultParserConstants {

  int EOF = 0;
  int FORMAL_COMMENT = 10;
  int MULTI_LINE_COMMENT = 11;
  int APPLY = 13;
  int ASSERT = 14;
  int ATTRIB = 15;
  int CODEBASE = 16;
  int COMMA = 17;
  int DATA = 18;
  int EXTENDS = 19;
  int FALSE = 20;
  int HERE = 21;
  int HOST = 22;
  int INCLUDE = 23;
  int PROPERTY = 24;
  int IPROPERTY = 25;
  int ENVPROPERTY = 26;
  int IENVPROPERTY = 27;
  int CONST = 28;
  int LAZY = 29;
  int LBRACE = 30;
  int LBRACKET = 31;
  int NULL = 32;
  int OPTIONAL = 33;
  int PARENT = 34;
  int PROCESS = 35;
  int RBRACE = 36;
  int RBRACKET = 37;
  int REFPARTSEP = 38;
  int ROOT = 39;
  int SEMICOLON = 40;
  int TBD = 41;
  int THIS = 42;
  int TRUE = 43;
  int VECTOREND = 44;
  int VECTORSTART = 45;
  int UNIQUE = 46;
  int OPSTART = 47;
  int OPEND = 48;
  int SUM = 49;
  int MINUS = 50;
  int TIMES = 51;
  int DIV = 52;
  int MOD = 53;
  int CONCAT = 54;
  int APPEND = 55;
  int EQ = 56;
  int NE = 57;
  int GE = 58;
  int LE = 59;
  int GT = 60;
  int LT = 61;
  int AND = 62;
  int OR = 63;
  int XOR = 64;
  int NOT = 65;
  int IMPLIES = 66;
  int IF = 67;
  int THEN = 68;
  int ELSE = 69;
  int FI = 70;
  int SWITCH = 71;
  int ENDSWITCH = 72;
  int VAR = 73;
  int WORD = 74;
  int SPECIAL = 75;
  int LETTER = 76;
  int DIGIT = 77;
  int STRING = 78;
  int MULTILINESTRING = 79;
  int INTEGER = 80;
  int FLOAT_BASE = 81;
  int EXPONENT = 82;
  int DOUBLE = 83;
  int LONG = 84;
  int FLOAT = 85;
  int BYTEARRAY = 86;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "<token of kind 9>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "\"APPLY\"",
    "\"ASSERT\"",
    "\"ATTRIB\"",
    "\"#codebase\"",
    "\",\"",
    "\"DATA\"",
    "\"extends\"",
    "\"false\"",
    "\"HERE\"",
    "\"HOST\"",
    "\"#include\"",
    "\"PROPERTY\"",
    "\"IPROPERTY\"",
    "\"ENVPROPERTY\"",
    "\"IENVPROPERTY\"",
    "\"CONSTANT\"",
    "\"LAZY\"",
    "\"{\"",
    "\"[\"",
    "\"NULL\"",
    "\"OPTIONAL\"",
    "\"PARENT\"",
    "\"PROCESS\"",
    "\"}\"",
    "\"]\"",
    "\":\"",
    "\"ROOT\"",
    "\";\"",
    "\"TBD\"",
    "\"THIS\"",
    "\"true\"",
    "\"|]\"",
    "\"[|\"",
    "\"--\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"++\"",
    "\"<>\"",
    "\"==\"",
    "\"!=\"",
    "\">=\"",
    "\"<=\"",
    "\">\"",
    "\"<\"",
    "\"&&\"",
    "\"||\"",
    "\"x|\"",
    "\"!\"",
    "\"->\"",
    "\"IF\"",
    "\"THEN\"",
    "\"ELSE\"",
    "\"FI\"",
    "\"SWITCH\"",
    "\"ENDSWITCH\"",
    "\"VAR\"",
    "<WORD>",
    "<SPECIAL>",
    "<LETTER>",
    "<DIGIT>",
    "<STRING>",
    "<MULTILINESTRING>",
    "<INTEGER>",
    "<FLOAT_BASE>",
    "<EXPONENT>",
    "<DOUBLE>",
    "<LONG>",
    "<FLOAT>",
    "<BYTEARRAY>",
  };

}
